#!/usr/bin/env node
/* Download the site's webfonts from Google and rewrite them as a local
 * stylesheet, so a visitor's browser never talks to fonts.googleapis.com or
 * fonts.gstatic.com.
 *
 * Why bother, when the Google CDN is fast:
 *
 *   - Every visitor to every page announced themselves to a third party
 *     before a word of the site rendered. Nothing here needs that.
 *   - The <link> to fonts.googleapis.com is render-blocking, and it is a
 *     separate origin: DNS, TLS and the CSS round-trip all happen before the
 *     font files are even discovered. Self-hosted, the woff2 sits on the same
 *     connection as the page.
 *   - Cross-site font caching was partitioned by every major browser in 2020,
 *     so the "someone else already cached it" argument no longer holds.
 *
 * Subsetting is preserved exactly as Google generates it: one @font-face per
 * subset, each with its unicode-range, so a browser still downloads only the
 * ranges the page actually uses. Ukrainian needs cyrillic; French, Spanish and
 * Portuguese need latin-ext; nothing here needs vietnamese, so it is dropped.
 *
 * Japanese is deliberately NOT self-hosted, and not loaded at all. See the
 * note on CJK below.
 *
 * Idempotent: re-running redownloads and rewrites in place. Files that Google
 * has revved (the v21 in the URL) change name, so stale ones are pruned.
 *
 * Run: node tools/fetch-fonts.js
 */
'use strict';
const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.join(__dirname, '..');
const FONT_DIR = path.join(ROOT, 'assets/fonts');
const OUT_CSS = path.join(ROOT, 'assets/css/fonts.css');

// Asking as a current Chrome is what makes Google serve woff2 rather than the
// ttf it hands to unrecognised clients.
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) ' +
  'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36';

const SRC = 'https://fonts.googleapis.com/css2' +
  '?family=Cormorant+Garamond:ital,wght@0,300;0,400;1,300;1,400' +
  '&family=DM+Mono:wght@300;400;500' +
  '&display=swap';

// The site is English, French, Spanish, Portuguese and Ukrainian. Vietnamese
// costs four more files to host and can never be reached; if Vietnamese is
// ever added the text falls back to a system serif rather than breaking.
const KEEP = new Set(['latin', 'latin-ext', 'cyrillic', 'cyrillic-ext']);

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

async function main() {
  const res = await fetch(SRC, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`Google returned ${res.status} for the CSS`);
  const css = await res.text();

  fs.mkdirSync(FONT_DIR, { recursive: true });

  // Each rule is preceded by a /* subset */ comment naming its unicode-range.
  const blocks = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)];
  if (!blocks.length) throw new Error('no @font-face blocks parsed; Google changed the format');

  const kept = [];
  const wanted = new Set();
  let skipped = 0;

  for (const [, subset, rule] of blocks) {
    if (!KEEP.has(subset)) { skipped++; continue; }
    const family = /font-family:\s*'([^']+)'/.exec(rule)[1];
    const style = /font-style:\s*(\w+)/.exec(rule)[1];
    const weight = /font-weight:\s*(\d+)/.exec(rule)[1];
    const url = /url\((https:\/\/[^)]+\.woff2)\)/.exec(rule)[1];

    const name = `${slug(family)}-${style}-${weight}-${subset}.woff2`;
    wanted.add(name);
    const dest = path.join(FONT_DIR, name);

    if (!fs.existsSync(dest)) {
      const f = await fetch(url, { headers: { 'User-Agent': UA } });
      if (!f.ok) throw new Error(`${f.status} fetching ${url}`);
      fs.writeFileSync(dest, Buffer.from(await f.arrayBuffer()));
      console.log(`  downloaded ${name}`);
    }
    // fonts.css lives in assets/css/, the woff2 in assets/fonts/.
    kept.push(rule.replace(/url\(https:\/\/[^)]+\.woff2\)/, `url(../fonts/${name})`));
  }

  // Google revs its URLs; a renamed file would otherwise linger forever.
  let pruned = 0;
  for (const f of fs.readdirSync(FONT_DIR)) {
    if (f.endsWith('.woff2') && !wanted.has(f)) {
      fs.unlinkSync(path.join(FONT_DIR, f));
      console.log(`  pruned     ${f}`);
      pruned++;
    }
  }

  const header = `/* GENERATED by tools/fetch-fonts.js -- do not edit by hand.
 *
 * Self-hosted copies of the Google Fonts the site used to link at runtime.
 * Subsets and unicode-ranges are Google's own, so the browser still fetches
 * only the ranges a page needs. The vietnamese subset is dropped; the site
 * has no Vietnamese text.
 *
 * Both families are licensed under the SIL Open Font License 1.1, which
 * permits redistribution including self-hosting:
 *   Cormorant Garamond  Catharsis Fonts    https://fonts.google.com/specimen/Cormorant+Garamond
 *   DM Mono             Colophon Foundry   https://fonts.google.com/specimen/DM+Mono
 *
 * No Japanese face is loaded. Noto Sans JP ships as ~124 subset files PER
 * WEIGHT, and japanese.html needs two weights; self-hosting ~250 files to
 * style one page's vocabulary list is a poor trade. That page uses the
 * system CJK sans instead -- Hiragino on Apple, Yu Gothic on Windows, Noto
 * on Android -- which costs no download at all.
 */
`;

  fs.writeFileSync(OUT_CSS, header + '\n' + kept.join('\n') + '\n');
  console.log(`\n${kept.length} faces written to assets/css/fonts.css ` +
    `(${skipped} skipped as unused subsets, ${pruned} stale files pruned).`);
}

main().catch((e) => { console.error(e.message); process.exit(1); });
